<a href="https://colab.research.google.com/github/archie46/Deep-Learning-Lab/blob/main/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%tensorflow_version 1.x

ValueError: ignored

In [ ]:
import tensorflow
print(tensorflow.__version__)

In [ ]:
import numpy as np

In [ ]:
a = np.array([10,12,13])
b = np.array([1,2,3])

In [ ]:
np.dot(a,b)

73

In [ ]:
x = np.array([[1,2,3],
             [4,5,6]])

In [ ]:
x = [1,2,3]
y = [1,7,8]
print(x+y)

[1, 2, 3, 1, 7, 8]


In [ ]:
np.add(a,b)

array([11, 14, 16])

In [ ]:
import numpy as np
import tensorflow
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

In [ ]:
layer_1 = Dense(units=3,activation="sigmoid")
layer_2 = Dense(units=1,activation="sigmoid")
model = Sequential([layer_1,layer_2])

In [ ]:
x = np.array([[200.0,17.0],
              [120.0,5.0],
              [425.0,20.0],
              [212.0,18.0]])
y = np.array([1,0,0,1])

In [ ]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy())
model.fit(x,y)

1/1 [==============================] - 1s 677ms/step - loss: 0.6931


In [ ]:
print(model.predict(np.array([[205,20]])))

1/1 [==============================] - 0s 216ms/step
[[0.5]]


# **Horizontal vector**

In [ ]:
import numpy as np
lst = [10,20,30,40,50]
vctr = np.array(lst)
print("Vector Created From A List:")
print(vctr)

Vector Created From A List:
[10 20 30 40 50]


# Vertical vector

In [ ]:
import numpy as np
lst = [[2],
       [4],
       [6],
       [10]]
vctr = np.array(lst)
print("Vector Created From A List:")
print(vctr)

Vector Created From A List:
[[ 2]
 [ 4]
 [ 6]
 [10]]


In [ ]:
import numpy as np
lst1 = [10,20,30,40,50]
lst2 = [1,2,3,4,5]

vctr1 = np.array(lst1)
vctr2 = np.array(lst2)

print("Vector Created From A List 1:")
print(vctr1)
print("Vector Created From A List 2:")
print(vctr2)

vctr_add = vctr1 + vctr2
print("Addition of Two Vectors:",vctr_add)

Vector Created From A List 1:
[10 20 30 40 50]
Vector Created From A List 2:
[1 2 3 4 5]
Addition of Two Vectors: [11 22 33 44 55]


In [ ]:
import tensorflow as tf
msg = tf.constant("Hello To Tensorflow!")
sess = tf.compat.v1.Session()
print(sess.run(msg))

Hello To Tensorflow!


RuntimeError: ignored

In [ ]:
import tensorflow as tf
b = tf.Variable(tf.zeros((100,)))
W = tf.Variable(tf.random.uniform((784,100),-1,1))

x = tf.placeholder(tf.float32,(1,784))

h = tf.nn.relu(tf.matmul(x,W)+b)

RuntimeError: ignored

In [ ]:
# importing tensorflow
import tensorflow as tf
# creating nodes in computation graph
node = tf.Variable(tf.zeros([2,2]))
 # running computation graph
with tf.compat.v1.Session() as sess:
   # initialize all global variables
   sess.run(tf.compat.v1.global_variables_initializer())
   # evaluating node
   print("Tensor value before addition:\n",sess.run(node))
   # elementwise addition to tensor
   node = node.assign(node + tf.ones([2,2]))
   # evaluate node again
   print("Tensor value after addition:\n", sess.run(node))

TypeError: ignored