<a href="https://colab.research.google.com/github/archie46/Deep-Learning-Lab/blob/main/Lab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
tensor1 = tf.constant(3.4,tf.float16,name="x")
print(tensor1)

tf.Tensor(3.4, shape=(), dtype=float16)


In [ ]:
tensor22 = tf.constant(5,tf.int16,name="x")
print(tensor22)

tf.Tensor(5, shape=(), dtype=int16)


In [ ]:
tensor2 = tf.constant(5.6,tf.float16,name="x")
tf.print(tensor2)

5.6015625


In [ ]:
tensor3 = tf.constant("CVR",tf.string,name="x")
tf.print(tensor3)

CVR


In [ ]:
tf.print(tf.add(tensor1,tensor2))

9


In [ ]:
layer1 = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
tf.print(layer1)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [10 11 12]]


In [ ]:
layer2 = tf.constant([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
tf.print(layer1)

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [10 11 12]]


In [ ]:
tf.print(tf.add(layer1,layer2))

[[2 4 6]
 [8 10 12]
 [14 16 18]
 [20 22 24]]


In [ ]:
tf.print(tf.multiply(layer1,layer2,1))

[[1 4 9]
 [16 25 36]
 [49 64 81]
 [100 121 144]]


In [ ]:
import numpy as np
lst = [10,20,30,40,50]
vctr = np.array(lst)
print("Vector Created From A List:")
print(vctr)