<a href="https://colab.research.google.com/github/archie46/Deep-Learning-Lab/blob/main/Lab4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [ ]:
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
y

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 0.08331364,  0.31788486,  0.6204981 , -0.16194667],
       [ 0.08331364,  0.31788486,  0.6204981 , -0.16194667],
       [ 0.08331364,  0.31788486,  0.6204981 , -0.16194667]],
      dtype=float32)>

In [ ]:
model.layers

In [ ]:
model.pop()
print(len(model.layers))  # 2

2


In [ ]:
layer = layers.Dense(3)
layer.weights  # Empty

[]

In [ ]:
import numpy as np
x = np.array([[200.0,17.0]])
model = keras.Sequential(
    [
      layers.Dense(units=3,activation='sigmoid',name='layer1')
    ]
)

In [ ]:
model.add(layers.Dense(units=2,activation='sigmoid',name='layer2'))

In [ ]:
tf.print(model.layers)

In [ ]:
model.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7f53a0c71cd0>>

In [ ]:
model.pop()

In [ ]:
tf.print(model.layers)

In [ ]:
model.summary

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7f53a0c71cd0>>

In [ ]:
model